companies/urls.py
from django.urls import path

from . import views


app_name = 'companies'
urlpatterns = [
    path(
        'create/',
        views.CompanyCreateForm.as_view(),
        name='companycreation'
    ),
    path(
        '<int:pk>/delete/',
        views.CompanyDeleteView.as_view(),
        name='delete'
    ),
    path(
        '<int:pk>/',
        views.CompanyDetailView.as_view(),
        name='detail'
    ),
    path(
        '',
        views.CompanyListView.as_view(),
        name='list'
    ),
    path(
        '<int:pk>/update/',
        views.CompanyUpdateView.as_view(),
        name='update'
    ),
]

jobs/urls.py
from django.urls import path

from . import views


app_name = 'jobs'
urlpatterns = [
    path(
        'for/<int:company_id>/create/',
        views.JobCreateForm.as_view(),
        name='jobcreation'
    ),
    path(
        '<int:pk>/delete/',
        views.JobDeleteView.as_view(),
        name='delete'
    ),
    path(
        '<int:pk>/',
        views.JobDetailView.as_view(),
        name='detail'
    ),
    path(
        '<int:pk>/update/',
        views.JobUpdateView.as_view(),
        name='update'
    ),

    # path(
    #     '',
    #     views.JobListView.as_view(),
    #     name='list'
    # ),
]

jobysite/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView

from django.conf import settings
from django.conf.urls.static import static


# app_name = 'jobysite'
urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('applications/', include('applications.urls')),
    path('users/', include('users.urls')),
    path('companies/', include('companies.urls')),
    path('jobs/', include('jobs.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

jobysite/templates/about.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="row">
  <div class="col-sm-8 offset-sm-2">
    <h4>Welcome to Jobylite, Jobylon's little nephew!</h4>
    <div>
      {% lorem 6 p random %}
    </div>
  </div>
</div>


{% endblock %}

jobysite/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>

<html>
<head>
  <style>
  .navbar {
    background-color: #69cc00;
    color: #e6ffcc !important;
  }
  .chapeau {
    background-color: #c1ff80;
    color: #206040;
    height: 160px;
  }
  .row {
    padding-top: 40px;
    padding-left: 20px;
    padding-right: 20px;
    padding-bottom: 20px;
  }
  .col-sm-7 {
    padding-bottom: 20px;
  }
  .list-group-item {
    word-wrap: break-word;
  }
  .logo {
    padding-left: 20px;
  }
  </style>
  {% block head %}
  <meta charset="utf-8">
  <!--
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
  <script src="https://cdn.ckeditor.com/ckeditor5/10.0.0/classic/ckeditor.js"></script>
  <title>{% block title %}{% endblock %}Jobylite</title>
  {% endblock %}
</head>
<body>
  <main>
    {% block navbar %}
      {% include 'navbar.html' %}
    {% endblock navbar %}

    {% block chapeau %}
    <div class="container-fluid chapeau"></div>
    {% endblock %}

    {% block content %}
    <div class="row">
      <div class="col-sm-6 offset-sm-3">
      </div>
    </div>
    {% endblock %}

  </main>
</body>
</html>

jobysite/templates/base_no_nav.html
{% extends 'base.html' %}

{% block navbar %}{% endblock %}
{% block content %}{% endblock %}

jobysite/templates/delete.html
{% extends 'base.html' %}

{% block title %}Create a new app{% endblock %}

{% block content %}
<div class="row">
  <div class="col-sm-8 offset-sm-2">
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm" />
    </form>
  </div>
</div>
{% endblock %}

jobysite/templates/home.html
<!-- templates/home.html -->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="row">
  <div class="col-sm-8 offset-sm-2">
    {% if user.is_authenticated %}
      Hi {{ user.username }}!
      <p><a href="{% url 'logout' %}">logout</a></p>
    {% else %}
      <p>You are not logged in</p>
      <a href="{% url 'login' %}">login</a> |
      <a href="{% url 'users:signup' %}">signup</a>
    {% endif %}
  </div>
</div>

{% endblock %}

jobysite/templates/navbar.html
<nav class="navbar navbar-expand-sm" role="navigation">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">Jobylite</a>
        <button class="navbar-toggler border-0" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
            &#9776;
        </button>
        <div class="collapse navbar-collapse" id="exCollapsingNavbar">
            <ul class="nav navbar-nav">
                <li class="nav-item"><a href="{% url 'about' %}" class="nav-link">About</a></li>
                {% if user.is_authenticated %}
                <li class="nav-item"><a href="{% url 'companies:list' %}" class="nav-link">Companies</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav flex-row justify-content-between ml-auto">
                {% if not user.is_authenticated %}
                <li class="nav-item">
                  <a href="{% url 'login' %}" class="nav-link">
                  <button type="button" class="btn btn-outline-secondary">Login</button></a>
                </li>
                {% endif %}
                {% if user.is_authenticated %}
                <li class="nav-item">
                  <a href="{% url 'logout' %}" class="nav-link">
                  <button type="button" class="btn btn-outline-secondary">Logout</button></a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div id="modalPassword" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3>Forgot password</h3>
                <button type="button" class="close font-weight-light" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <p>Reset your password..</p>
            </div>
            <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
                <button class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

jobysite/templates/update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% crispy form form.helper %}


{% block content %}
<div class="row">
  <div class="col-sm-8 offset-sm-2">
    <form action="" method="post">{% csrf_token %}
        {% crispy form %}
    </form>
  </div>
</div>
{% endblock %}