applications/urls.py
from django.urls import path

from . import views


app_name = 'applications'
urlpatterns = [
    path(
        '<int:job_id>/apply/',
        views.ApplicationCreateForm.as_view(),
        name='applicationform'
    ),
    path(
        '<int:pk>/detail/',
        views.ApplicationDetailView.as_view(),
        name='detail'
    ),
    path(
        'thankyou/',
        views.thankyou,
        name='thankyou'
    ),
]

companies/urls.py
from django.urls import path

from . import views


app_name = 'companies'
urlpatterns = [
    path(
        'create/',
        views.CompanyCreateForm.as_view(),
        name='companycreation'
    ),
    path(
        '<int:pk>/delete/',
        views.CompanyDeleteView.as_view(),
        name='delete'
    ),
    path(
        '<int:pk>/',
        views.CompanyDetailView.as_view(),
        name='detail'
    ),
    path(
        '',
        views.CompanyListView.as_view(),
        name='list'
    ),
    path(
        '<int:pk>/update/',
        views.CompanyUpdateView.as_view(),
        name='update'
    ),
]

jobs/urls.py
from django.urls import path

from . import views


app_name = 'jobs'
urlpatterns = [
    path(
        'for/<int:company_id>/create/',
        views.JobCreateForm.as_view(),
        name='jobcreation'
    ),
    path(
        '<int:pk>/delete/',
        views.JobDeleteView.as_view(),
        name='delete'
    ),
    path(
        '<int:pk>/',
        views.JobDetailView.as_view(),
        name='detail'
    ),
    path(
        '<int:pk>/update/',
        views.JobUpdateView.as_view(),
        name='update'
    ),

    # path(
    #     '',
    #     views.JobListView.as_view(),
    #     name='list'
    # ),
]

jobysite/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView

from django.conf import settings
from django.conf.urls.static import static


# app_name = 'jobysite'
urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('applications/', include('applications.urls')),
    path('users/', include('users.urls')),
    path('companies/', include('companies.urls')),
    path('jobs/', include('jobs.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

applications/models.py
from django.db import models
from django.urls import reverse

from jobs.models import Job
from times.models import TimeStampedModel
from users.models import User


class Application(TimeStampedModel):
    name = models.CharField(max_length=60)
    email = models.EmailField()
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    photo = models.ImageField(blank=True, upload_to='photos')
    cv = models.FileField(blank=True, upload_to='cvs')
    doc = models.FileField(blank=True, upload_to='docs')
    text = models.TextField(blank=True)
    is_evaluated = models.BooleanField(blank=True, default=False)
    is_candidate = models.BooleanField(blank=True, default=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('applications:thankyou')

jobs/models.py
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.urls import reverse

from ckeditor.fields import RichTextField

# from commons.models import NameMixin
from companies.models import Company
from times.models import TimeStampedModel
from users.models import User


class Job(TimeStampedModel):
    title = models.CharField(max_length=200)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    description = RichTextField(max_length=5000, blank=True)
    # A list of questions (will receive own fields in Application)
    # questions = ArrayField(
    #     models.CharField(blank=True, max_length=200),
    #     size=3,
    #     blank=True,
    # )
    # question = models.CharField(max_length=200, blank=True)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('jobs:detail', kwargs={'pk': self.id})

jobs/forms.py
from django import forms
from django.contrib.postgres.forms import SplitArrayField
from django.contrib.postgres.forms import SplitArrayWidget
from django.db import models
from django.forms import ModelForm

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout
from crispy_forms.layout import Submit

from .models import Job


class JobCreationForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post' # this line sets your form's method to post
        self.helper.layout = Layout( # the order of the items in this layout is important
            'title',
            'description',
            Submit('submit', u'Submit', css_class='btn btn-success'),
        )

    # def __init__(self, *args, **kwargs):
    #
    #     super().__init__(*args, **kwargs)
    #
    #     # field 'questions'
    #     widget_base_field = self.fields['questions'].base_field.widget
    #     count_inputs = self.fields['questions'].max_length
    #     self.fields['questions'].widget = SplitInputsArrayWidget(
    #         widget_base_field,
    #         count_inputs,
    #         remove_trailing_nulls=True,
    #         attrs={'class': 'span12'}
    #     )

    class Meta:
        model = Job
        fields = ['title', 'description']



# class SplitInputsArrayWidget(SplitArrayWidget):
#
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#
#     def value_from_datadict(self, data, files, name):
#
#         value_from_datadict = super().value_from_datadict(data, files, name)
#
#         # convert a list to a string, with commas-separated values
#         value_from_datadict = ','.join(value_from_datadict)
#
#         return value_from_datadict
#
#     def render(self, name, value, attrs=None):
#
#         # if object has value, then
#         # convert a sting to a list by commas between values
#         if value is not None:
#             value = value.split(',')
#
#         return super().render(name, value, attrs=None)

jobs/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import UpdateView

from .forms import JobCreationForm
from companies.models import Company
from jobs.models import Job


class JobCreateForm(CreateView):
    form_class = JobCreationForm
    template_name = 'create.html'
    model_name = form_class.Meta.model._meta.verbose_name

    def form_valid(self, form):
        # Set company
        form.instance.company_id = self.kwargs.get('company_id')
        # form.instance.job = self.object
        # form.instance.save()
        return super().form_valid(form)


class JobDeleteView(DeleteView):
    # form_class = JobCreationForm
    model = Job
    template_name = 'delete.html'
    success_url = reverse_lazy('companies:list')


class JobDetailView(DetailView):
    model = Job
    template_name = 'job.html'


class JobUpdateView(UpdateView):
    model = Job
    # instead of declaring fields
    form_class = JobCreationForm
    template_name = 'update.html'

jobs/templates/job.html
{% extends user.is_authenticated|yesno:"base.html,base_no_nav.html" %}

{% load thumbnail %}

{% block chapeau %}
<div class="container-fluid chapeau">
  <div class="row d-flex h-100">
    <div class="col text-sm-left text-center justify-content-center align-self-center logo">
      <a href="{% url 'companies:detail' object.company.id %}" title="Company">
        {% thumbnail view.object.company.logo "140x100" crop='center' as im %}
          <img class="rounded-circle align-middle" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
        {% endthumbnail %}
      </a>
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<div class="row">
  <div class="col-sm-7 offset-sm-1">
    <h4>We are looking for {{ view.object.title }}</h4>
    <div>
      {{ view.object.description|safe }}
    </div>
  </br>
    <div>
      <a href="{% url 'jobs:update' object.id %}" class="btn btn-secondary" role="button">Edit</a>
      <a href="{% url 'jobs:delete' object.id %}" class="btn btn-secondary" role="button">Delete</a>
    </div>
{{ request.url }}
</div>
<div class="col-sm-3">
  {% if object.application_set.exists %}
  <h5>Applicants</h5>
  <div class="list-group">
    {% for application in object.application_set.all %}
        {% if application.is_evaluated %}
        <a href="{% url 'applications:detail' application.id %}" class="list-group-item disabled">
          <div class="d-flex align-items-center justify-content-between">
            {{ application.name }}
            {% if application.is_candidate %}
              <span class="badge badge-info badge-pill">Candidate</span>
            {% endif %}
          </div>
        </a>
        {% else %}
        <a href="{% url 'applications:detail' application.id %}" class="list-group-item list-group-item-action">{{ application.name }}</a>
        {% endif %}
    {% endfor %}
  </div>
  {% else %}
  <h5>No applicants yet</h5>
  {% endif %}
</div>
</div>
{% else %}
<div class="row">
  <div class="col-sm-8 offset-sm-2">
    <h4>We are looking for {{ view.object.title }}</h4>
    <div>
      {{ view.object.description|safe }}
    </div>
  </br>
  </br>
  <p>
    Some info about the company..
  </p>
  <h3>{{ view.object.company.name }}</h3>
  <div>
    {{ view.object.company.description|safe }}
  </div>
  <div>
    Check out our website:
    <a href="{{ view.object.company.website }}" title="{{ view.object.company.website }}">
      {{ view.object.company.website }}
    </a>
  </div>
  <div>
    <p>
      E-mail for any questions: {{ view.object.company.email }}
    </p>
  </div>
  <div>
    <a href="{% url 'applications:applicationform' object.id %}" class="btn btn-success btn-block" role="button">Apply</a>
  </div>
  </div>
</div>
{% endif %}
{% endblock %}