companies/urls.py
from django.urls import path

from . import views


app_name = 'companies'
urlpatterns = [
    path(
        'create/',
        views.CompanyCreateForm.as_view(),
        name='companycreation'
    ),
    path(
        '<int:pk>/delete/',
        views.CompanyDeleteView.as_view(),
        name='delete'
    ),
    path(
        '<int:pk>/',
        views.CompanyDetailView.as_view(),
        name='detail'
    ),
    path(
        '',
        views.CompanyListView.as_view(),
        name='list'
    ),
    path(
        '<int:pk>/update/',
        views.CompanyUpdateView.as_view(),
        name='update'
    ),
]

jobs/urls.py
from django.urls import path

from . import views


app_name = 'jobs'
urlpatterns = [
    path(
        'for/<int:company_id>/create/',
        views.JobCreateForm.as_view(),
        name='jobcreation'
    ),
    path(
        '<int:pk>/delete/',
        views.JobDeleteView.as_view(),
        name='delete'
    ),
    path(
        '<int:pk>/',
        views.JobDetailView.as_view(),
        name='detail'
    ),
    path(
        '<int:pk>/update/',
        views.JobUpdateView.as_view(),
        name='update'
    ),

    # path(
    #     '',
    #     views.JobListView.as_view(),
    #     name='list'
    # ),
]

jobysite/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView

from django.conf import settings
from django.conf.urls.static import static


# app_name = 'jobysite'
urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('applications/', include('applications.urls')),
    path('users/', include('users.urls')),
    path('companies/', include('companies.urls')),
    path('jobs/', include('jobs.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

applications/models.py
from django.db import models
from django.urls import reverse

from jobs.models import Job
from times.models import TimeStampedModel
from users.models import User


class Application(TimeStampedModel):
    name = models.CharField(max_length=60)
    email = models.EmailField()
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    photo = models.ImageField(blank=True, upload_to='photos')
    cv = models.FileField(blank=True, upload_to='cvs')
    doc = models.FileField(blank=True, upload_to='docs')
    text = models.TextField(blank=True)
    is_evaluated = models.BooleanField(blank=True, default=False)
    is_candidate = models.BooleanField(blank=True, default=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('applications:thankyou')

companies/models.py
from django.urls import reverse
from django.db import models

from ckeditor.fields import RichTextField

# from commons.models import NameMixin
from jobysite.settings import AUTH_USER_MODEL
from times.models import TimeStampedModel
from users.models import User


class Company(TimeStampedModel):
    name = models.CharField(max_length=200)
    description = RichTextField(max_length=5000, blank=True)
    website = models.URLField(blank=True)
    email = models.EmailField(blank=True)
    logo = models.ImageField(blank=True, upload_to='logos')
    users = models.ManyToManyField(User)
    # related_name limitations now: no User.company_set
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name='+')

    class Meta:
        verbose_name_plural = 'companies'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('companies:list')


# class Job(NameMixin, TimeStampedModel):
#     title = models.CharField(max_length=200)
#     company = models.ForeignKey(Company, on_delete=models.CASCADE)
#     description = models.TextField(max_length=1000, blank=True)
#     # A list of questions separated by commas (will receive own fields in Application)
#     questions = ArrayField(models.CharField(blank=True, max_length=200), size=6)
#
#     def __str__(self):
#         return self.title
#
#     def get_absolute_url(self):
#         return reverse('company')


# class Applicant(NameMixin, TimeStampedModel):
#     name = models.CharField(max_length=200)
#     question = models.TextField
#     job = models.ForeignKey(Job, on_delete=models.CASCADE)
#     photo = models.ImageField(blank=True, upload_to='photos/')
#     cv = models.FileField(blank=True, upload_to='cvs/')
#     doc = models.FileField(blank=True, upload_to='docs/')
#     text = models.TextField(blank=True)
#
#     def __str__(self):
#         return self.name

jobs/models.py
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.urls import reverse

from ckeditor.fields import RichTextField

# from commons.models import NameMixin
from companies.models import Company
from times.models import TimeStampedModel
from users.models import User


class Job(TimeStampedModel):
    title = models.CharField(max_length=200)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    description = RichTextField(max_length=5000, blank=True)
    # A list of questions (will receive own fields in Application)
    # questions = ArrayField(
    #     models.CharField(blank=True, max_length=200),
    #     size=3,
    #     blank=True,
    # )
    # question = models.CharField(max_length=200, blank=True)


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('jobs:detail', kwargs={'pk': self.id})

companies/forms.py
from django import forms
from django.forms import ModelForm

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout
from crispy_forms.layout import Submit

from .models import Company
# from .models import Job


class CompanyCreationForm(ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post' # this line sets your form's method to post
        self.helper.layout = Layout( # the order of the items in this layout is important
            'logo',
            'name',
            'description',
            'website',
            'email',

            Submit('submit', u'Submit', css_class='btn btn-success'),
        )

    class Meta:
        model = Company
        fields = ['name', 'description', 'website', 'email', 'logo']


# class JobCreationForm(ModelForm):
#
#     class Meta:
#         model = Job
#         fields = ['title', 'description', 'questions']

companies/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import UpdateView

from .forms import CompanyCreationForm
from .models import Company

@method_decorator(login_required, name='dispatch')
class CompanyCreateForm(CreateView):
    form_class = CompanyCreationForm
    template_name = 'create.html'
    # view way of passing extra context, less preferable
    model_name = form_class.Meta.model._meta.verbose_name

    # context to facilite using the same template
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['templata'] = 'Company'
    #     return context


    def form_valid(self, form):
        response = super().form_valid(form)
        # Add user to created company
        self.object.users.add(self.request.user)
        # Set created company as user's current company
        self.request.user.company = self.object
        self.request.user.save()
        logo = form.cleaned_data['logo']
        return super().form_valid(form)


class CompanyDeleteView(DeleteView):
    # form_class = JobCreationForm
    model = Company
    template_name = 'delete.html'
    success_url = reverse_lazy('companies:list')


class CompanyDetailView(DetailView):
    model = Company
    template_name = 'company.html'


class CompanyListView(ListView):
    model = Company
    template_name = 'companies.html'


class CompanyUpdateView(UpdateView):
    form_class = CompanyCreationForm
    model = Company
    template_name = 'update.html'

    def get_success_url(self):
        return reverse('companies:detail', kwargs={'pk': self.object.id})

companies/templates/companies.html
{% extends 'base.html' %}

{% block title %}Create a new app{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<div class="row">
  <div class="col-sm-7 offset-sm-1">
    <h4>Welcome to your dashboard!</h4>
    {% lorem 2 p %}
    <a href="{% url 'companies:companycreation' %}" class="btn btn-primary btn-block" role="button">Create New Company</a>
  </div>
  {% if user.company_set.exists %}
  <div class="col-sm-3">
    <div class="list-group">
    {% for company in user.company_set.all %}
        <a href="{% url 'companies:detail' company.id %}" class="list-group-item list-group-item-info list-group-item-action">{{ company.name }}</a>
    {% endfor %}
    {% endif %}
    </div>
  </div>
</div>
{% else %}
<div class="row">
  <div class="col-sm-8 offset-sm-2">
    You have to login to view this page.
  </div>
</div>
{% endif %}

{% endblock %}

companies/templates/company.html
{% extends user.is_authenticated|yesno:"base.html,base_no_nav.html" %}

{% load thumbnail %}

{% block chapeau %}
<div class="container-fluid chapeau">
  <div class="row d-flex h-100">
    <div class="col text-sm-left text-center justify-content-center align-self-center logo">
      {% thumbnail company.logo "140x100" crop='center' as im %}
      <img class="rounded-circle align-middle" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
      {% endthumbnail %}
    </div>
  </div>
</div>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-sm-7 offset-sm-1">
    {% if user.is_authenticated %}
    <div class="">
      <a href="{% url 'jobs:jobcreation' company.id %}" class="btn btn-primary btn-lg" role="button">
        <span style="font-size:smaller;">Create New Job</span>
      </a>
    </div>
    </br>
    </br>
    {% endif %}
    <div>
      <h4>{{ company.name }}</h4>
    </div>
    <div>
      {{ company.description|safe }}
    </div>
    <div>
      Website:
      <a href="{{ company.website }}" title="{{ company.website }}">{{ company.website }}</a>
    </div>
    <div>
      E-mail:
      {{ company.email }}
    </div>
    {% if user.is_authenticated %}
  </br>
    <div>
      <a href="{% url 'companies:update' company.id %}" class="btn btn-secondary" role="button">Edit</a>
      <a href="{% url 'companies:delete' company.id %}" class="btn btn-secondary" role="button">Delete</a>
    </div>
  </br>
    <h5>Create a new job ad..</h5>
<div>
  {% lorem %}
</div>
  </br>
  <div class="">
    <a href="{% url 'jobs:jobcreation' company.id %}" class="btn btn-primary btn-lg" role="button">
      <span style="font-size:smaller;">Create New Job</span>
    </a>
  </div>
    {% endif %}
  </br>
  </div>
  <div class="col-sm-3">
    {% if object.job_set.exists %}
      <div class="list-group">
        {% for job in object.job_set.all %}
        <a href="{% url 'jobs:detail' job.id %}" class="list-group-item list-group-item-secondary list-group-item-action">
          <div class="d-flex align-items-center justify-content-between">
            {{ job.title }}
            {% if user.is_authenticated %}
            <span class="badge badge-info badge-pill">{{ job.application_set.count }}</span>
            {% else %}
                {% if job.application_set.count <= 10 %}
                <span class="badge badge-info badge-pill">New</span>
                {% endif %}
            {% endif %}
          </div>
        </a>
        {% endfor %}
      </div>
    {% endif %}
  </div>
</div>
</br></br></br></br></br>

{% endblock %}

companies/templates/create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% crispy form form.helper %}

{% block title %}Create a new app{% endblock %}

{% block content %}
<div class="row">
  <div class="col-sm-8 offset-sm-2">
    <h2>New {{ view.model_name }}</h2>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {% crispy form %}
    </form>
  </div>
</div>
{% endblock %}